# @package _group_
kwargs:
  devices : -1 # gpus is deprecated
  accelerator: cuda
  max_epochs: 40
  #gradient_clip_val: 1
  #DeviceStatsMonitor : None
  limit_train_batches: 25000
  val_check_interval: 2600
  log_every_n_steps: 250
  precision: 32
  detect_anomaly: False
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 8
  use_distributed_sampler: False
checkpoint_kwargs:
  verbose: True
  save_top_k: 5
  save_last: True
  every_n_epochs: 1 # period is deprecated
  monitor: val_ssim_fid100_f1_total_mean
  mode: max