# @package _group_
data_root_dir: C:\Users\zhang\dev\lama/celeba-hq-dataset/
out_root_dir: C:\Users\zhang\dev\lama/experiments/
tb_dir: C:\Users\zhang\dev\lama/tb_logs/
pretrained_models: C:\Users\zhang\dev\lama/
